### ISSUE TITLE
"joinLeft" is not working when joining a clock with a DataFrame in DataBricks

### ISSUE THREAD

**Issue by LeoDashTM** [databricks/databricks-accelerators#1]
Hello @pohlposition 

The `joinLeft` is not working for me:
```
# Flint

print( sc.version )
from ts.flint import _version
print( _version.get_versions() )

n = spark.read.format('csv').options(header='true', inferSchema='true').load('test.txt')

from ts.flint import FlintContext, clocks
from ts.flint import utils
  
fc = FlintContext( sqlContext )

r = fc.read \
    .option('isSorted', False) \
    .option('timeUnit', 's') \
    .dataframe( n )

r.show(truncate=False)
print( r )
r.printSchema()

l = clocks.uniform(fc, '30s', begin_date_time='2018-8-1 5:55:35', end_date_time='2018-08-01 05:59:05')
print( type( l ) )
print( l )
print( l.count() )
l.printSchema()

j = l.leftJoin(r)
```

With the output being:
```
2.3.1
time
+-------------------+---------------+------------+
|time               |MemPercentG    |CpuPercentG |
+-------------------+---------------+------------+
|2018-08-01 05:55:35|0.0030517578125|0.002331024 |
|2018-08-01 05:58:05|0.0030517578125|0.0031538776|
|2018-08-01 05:59:05|0.0030517578125|0.0030176123|
+-------------------+---------------+------------+

TimeSeriesDataFrame[time: timestamp, MemPercentG: double, CpuPercentG: double]
root
 |-- time: timestamp (nullable = true)
 |-- MemPercentG: double (nullable = true)
 |-- CpuPercentG: double (nullable = true)

<class 'ts.flint.dataframe.TimeSeriesDataFrame'>
TimeSeriesDataFrame[time: timestamp]
root
 |-- time: timestamp (nullable = true)

java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.ExprCode.value()Ljava/lang/String;
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-911439891027714> in <module>()
     28 l.printSchema()
     29 
---> 30 j = l.leftJoin(r)
     31 
     32 # l.show(truncate=False)



/databricks/python/lib/python3.5/site-packages/ts/flint/dataframe.py in leftJoin(self, right, tolerance, key, left_alias, right_alias)
    606         tolerance = self._timedelta_ns('tolerance', tolerance, default='0ns')
    607         scala_key = utils.list_to_seq(self._sc, key)
--> 608         tsrdd = self.timeSeriesRDD.leftJoin(right.timeSeriesRDD, tolerance, scala_key, left_alias, right_alias)
    609         return TimeSeriesDataFrame._from_tsrdd(tsrdd, self.sql_ctx)
    610 

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o3324.leftJoin.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.ExprCode.value()Ljava/lang/String;
	at org.apache.spark.sql.TimestampCast$class.doGenCode(TimestampCast.scala:77)
	at org.apache.spark.sql.NanosToTimestamp.doGenCode(TimestampCast.scala:31)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:111)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:108)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:108)
	at org.apache.spark.sql.catalyst.expressions.Alias.genCode(namedExpressions.scala:143)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext$$anonfun$24$$anonfun$apply$5.apply(CodeGenerator.scala:1367)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext$$anonfun$24$$anonfun$apply$5.apply(CodeGenerator.scala:1366)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext$$anonfun$24.apply(CodeGenerator.scala:1366)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext$$anonfun$24.apply(CodeGenerator.scala:1366)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.withSubExprEliminationExprs(CodeGenerator.scala:1227)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.generateExpressionsForWholeStageWithCSE(CodeGenerator.scala:1365)
	at org.apache.spark.sql.execution.ProjectExec.doConsume(basicPhysicalOperators.scala:67)
	at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:181)
	at org.apache.spark.sql.execution.RDDScanExec.consume(ExistingRDD.scala:176)
	at org.apache.spark.sql.execution.RDDScanExec.doProduce(ExistingRDD.scala:221)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:190)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:187)
	at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
	at org.apache.spark.sql.execution.RDDScanExec.produce(ExistingRDD.scala:176)
	at org.apache.spark.sql.execution.ProjectExec.doProduce(basicPhysicalOperators.scala:50)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:190)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:187)
	at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
	at org.apache.spark.sql.execution.ProjectExec.produce(basicPhysicalOperators.scala:40)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doCodeGen(WholeStageCodegenExec.scala:530)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:582)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:150)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:138)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:190)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:187)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:108)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:108)
	at com.twosigma.flint.timeseries.NormalizedDataFrameStore.toOrderedRdd(TimeSeriesStore.scala:252)
	at com.twosigma.flint.timeseries.NormalizedDataFrameStore.orderedRdd(TimeSeriesStore.scala:237)
	at com.twosigma.flint.timeseries.TimeSeriesRDDImpl.orderedRdd(TimeSeriesRDD.scala:1346)
	at com.twosigma.flint.timeseries.TimeSeriesRDDImpl.leftJoin(TimeSeriesRDD.scala:1515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

By the way, what is the way to even display the contents of the clocks DataFrame?
The second to last commented out line (with the `.show` command) errors out, so I don't understand how `TimeSeriesDataFrame` is inheriting from a regular `DataFrame`, for which that method is available...
The `display` method also fails...

Anyways, what is wrong with the `leftJoin` here? Swapping left and right data frames also does not help.

Is this reproducible for you?

Please, advise, if I'm not using/calling it correctly or if it's a bug.

The flint libraries (the Scala and the Python ones) I installed on DataBricks via its UI (from the respective online repos, which might be dated). I also tried installing jar files: one compiled from the latest source off of GitHub by Two Sigma and the other one from this repo, still the same error.

Thanks.
[test.txt](https://github.com/databricks/databricks-accelerators/files/2536234/test.txt)

**Comment by LeoDashTM** [comment]
I tried running it “locally”, though, it’s my very first time running anything locally and the setup locally differs a little bit:
Spark is 2.3.2, version of flint as reported from pyspark is:
`{'date': '2018-07-25T19:19:11+0000', 'dirty': False, 'error': None, 'full-revisionid': '2e56267f357f89a15f2bdf5ba9af83dc34afe75e', 'version': '0.6.0'}`
(which for some reason doesn't get reported correctly on DataBricks)
The command line used was:
`spark-submit --jars ~/Downloads/flint_0_6_0_databricks.jar test.py`
and `test.py`'s contents are:
```
import pyspark
sc = pyspark.SparkContext()
sqlContext = pyspark.SQLContext(sc)
spark = sqlContext

from pyspark.sql.functions import *
from pyspark.sql.types import TimestampType

# MAIN CODE

print('==================================')
print( sc.version )
from ts.flint import _version
print( _version.get_versions() )
print('==================================')

n = spark.read.format('csv').options(header='true', inferSchema='true').load('/Users/levdashevskiy/Downloads/test.txt')

from ts.flint import FlintContext, clocks
from ts.flint import utils
  
fc = FlintContext( sqlContext )

n = n.withColumn( 'time', col('time').cast( 'timestamp' ) ) # needed locally

n.printSchema()

r = fc.read \
    .option('isSorted', False) \
    .option('timeUnit', 's') \
    .dataframe( n )

r.show(truncate=False)
print( r )
r.printSchema()

l = clocks.uniform(fc, '30s', begin_date_time='2018-8-1 5:55:35', end_date_time='2018-08-01 05:59:05')
print( type( l ) )
print( l )
print( l.count() )
l.printSchema()

j = l.leftJoin(r)

j.show()
print( j.count() )
print( '=====================' )
```

I had to have an extra call of converting the time column read in from the text file from string to a datetime one (don't have to do that within Databricks).
The join doesn't error out, but does not work as expected, the output is:
```
+--------------------+-----------+-----------+
|                time|MemPercentG|CpuPercentG|
+--------------------+-----------+-----------+
|50552-02-08 00:43...|       null|       null|
+--------------------+-----------+-----------+
```

**Comment by LeoDashTM** [comment]
Ok, actually just tried:
`spark-submit --packages com.twosigma:flint:0.6.0 test.py` locally and that did seem to produce the results I want!
So is it because locally I'm running 2.3.2 and it's 2.3.1 on DataBricks?
Am I able to upgrade DataBricks Spark instances from to 2.3.2 from 2.3.1?
If so how? I'm not seeing 2.3.2 in the set of available choices at the moment..., 2.3.1 is the highest version of Spark available on DB at the moment for DB 4.3. I'm not sure, which Spark version is contained in DB 5.0 beta version. And when will stable 5.1 come out?

Would really love to get it to work correctly with the current Spark 2.3.1

Thanks.

**Comment by LeoDashTM** [comment]
Update.
Just installed Spark 2.3.1 locally and running `pyspark --packages com.twosigma:flint:0.6.0` then executing each line from `test.py` seems to work correctly.
So the deal is indeed with the flavor of Spark installed on DataBricks then?

**Comment by LeoDashTM** [comment]
The same on local Spark 2.3.1 with `flint_0_6_0_databricks.jar` does not work correctly (but not with the original error code)...

The clock looks weird, for example:
```
>>> l = clocks.uniform(fc, '30s', begin_date_time='2018-08-01 5:55:35', end_date_time='2018-08-01 05:59:05')
>>> l.show(truncate=False)
+-----------------------+
|time                   |
+-----------------------+
|50552-02-05 14:23:200.0|
|50552-02-05 22:43:200.0|
|50552-02-06 07:03:200.0|
|50552-02-06 15:23:200.0|
|50552-02-06 23:43:200.0|
|50552-02-07 08:03:200.0|
|50552-02-07 16:23:200.0|
|50552-02-08 00:43:200.0|
+-----------------------+
```

But I say the goal is to make the maven repo work with the current DataBricks/Spark version by tweaking the latter, if possible...

And `l.show()` on DataBricks with the maven repo based library errors out:
```
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.ExprCode.value()Ljava/lang/String;
```

**Comment by LeoDashTM** [comment]
As a side note, retried the demo and it's failing at the 6th chunk with the summarizer... (That's the first time I've ran it) This is with DB flint from this repo...

**Comment by pohlposition** [comment]
A fix has been applied and merged.  Do a `git pull` to retrieve the latest lib/flint_0_6_0_databricks.jar
